# Buildpacks to include in builder
[[buildpacks]]
id = "knawd/rust"
version = "0.0.1"
uri = "../../buildpacks/rust"

[[order]]
    [[order.group]]
    id = "knawd/rust"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "dev.knawd.stacks.rust"
run-image = "quay.io/knawd/scratch"
build-image = "quay.io/knawd/stack:rust"